lemnia_customer_portal_homepage:
    path:     /
    defaults: { _controller: LemniaCustomerPortalBundle:HomePage:homePage }

lemnia_customer_portal_bill:
    path:     /bill
    defaults: { _controller: LemniaCustomerPortalBundle:Bill:listBill }

lemnia_customer_portal_indent:
    path:     /bill
    defaults: { _controller: LemniaCustomerPortalBundle:Indent:listIndent }

lemnia_customer_portal_subscription:
    path:     /
    defaults: { _controller: LemniaCustomerPortalBundle:Subsciption:listSubsciption }

lemnia_customer_portal_help:
    path:     /bill
    defaults: { _controller: LemniaCustomerPortalBundle:Help:help }

lemnia_customer_portal_listuser:
    path:     /bill
    defaults: { _controller: LemniaCustomerPortalBundle:User:listUser }

lemnia_customer_portal_user:
    path:     /bill
    defaults: { _controller: LemniaCustomerPortalBundle:User:user }