<?php

namespace Lemnia\CustomerPortalBundle\Repository;

/**
 * CarteBancaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteBancaireRepository extends \Doctrine\ORM\EntityRepository
{
}
