<?php

namespace Lemnia\CustomerPortalBundle\Repository;

/**
 * IntentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntentRepository extends \Doctrine\ORM\EntityRepository
{
}
