<?php

namespace Lemnia\CustomerPortalBundle\Repository;

/**
 * QuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRepository extends \Doctrine\ORM\EntityRepository
{
}
