<?php

namespace Lemnia\CustomerPortalBundle\Repository;

/**
 * SepaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SepaRepository extends \Doctrine\ORM\EntityRepository
{
}
